server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
      name: paiya-eventmanager
  profiles:
    active: dev

# OpenApi documentation
springdoc:
  api-docs:
    path: /doc
  swagger-ui:
    path: /swagger-ui.html

# Custom properties
paiya:
  popularityThreshold : 7.5