server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: default, cloud

# OpenApi documentation
springdoc:
  api-docs:
    path: /doc
  swagger-ui:
    path: /swagger-ui.html