server:
  port: 8010
  servlet:
    context-path: /paiya-eventmanager/api

# Database
spring:
  # Database
  data:
    mongodb:
      uri: mongodb+srv://tamsir225:L4fVcDT6Ynee4FMx@democluster.pfnfjyb.mongodb.net/paiya_eventmanager?retryWrites=true&w=majority&appName=DemoCluster
