server:
  port: 8011
  servlet:
    context-path: /api

# Database
spring:
  data:
    mongodb:
      host: ${PAIYA_DB_HOST}
      port: 27017
      database: paiya_eventmanager
      username: ${PAIYA_DB_USERNAME}
      password: ${PAIYA_DB_PASSWORD}
      authentication-database: paiya_eventmanager

